# -*- coding: utf-8 -*-
"""Proyeck Machine Learning V2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w0ibkZGpn0BX7xZtU0n_u90B_9H-Y7v_
"""

# === IMPORT LIBRARY ===
import pandas as pd
import re
import string
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# === DOWNLOAD NLTK RESOURCES ===
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

# === STOPWORDS ===
stop_words = set(stopwords.words("english"))

# === LOAD DATASET ===
data = pd.read_csv('reviews.csv')

# === DROP KOLOM TIDAK DIPAKAI ===
columns_to_drop = [
    's.no', 'helpfulVoteCount', 'images/0', 'images/1', 'images/2', 'images/3', 'images/4', 'images/5',
    'images/6', 'images/7', 'reviewID', 'reviewMetadata', 'productVariant',
    'reviewPosition', 'reviewTitle', 'reviewURL', 'verifiedPurchase',
    'videos/0', 'cleaned_review_text', 'rating', 'productASIN'
]
data.drop(columns=columns_to_drop, inplace=True, errors='ignore')

# === CEK DATA KOSONG & ISI NILAI DEFAULT ===
print(f"NaN reviewText : {data['reviewText'].isnull().sum()}")
print(f"NaN sentiment_score : {data['sentiment_score'].isnull().sum()}")

data['reviewText'].fillna('data Not Found', inplace=True)

# === LABEL SENTIMEN ===
def label_sentiment(score):
    if score > 0:
        return 'positive'
    elif score < 0:
        return 'negative'
    else:
        return 'neutral'

data['label'] = data['sentiment_score'].apply(label_sentiment)

# === PREPROCESSING TEXT ===
def preprocess_text(text):
    if pd.isna(text):
        return ""
    text = text.lower()  # lowercase
    text = re.sub(r'[^a-z\s]', '', text)  # hapus angka dan simbol
    tokens = word_tokenize(text)  # tokenisasi
    filtered = [word for word in tokens if word not in stop_words]  # hapus stopwords
    return " ".join(filtered)

# === APPLY PREPROCESSING ===
data["cleaned_text"] = data["reviewText"].apply(preprocess_text)

# === TF-IDF ===
tfidf = TfidfVectorizer(max_features=1000)
X = tfidf.fit_transform(data["cleaned_text"])

# === ENCODE LABEL ===
le = LabelEncoder()
y = le.fit_transform(data["label"])

# Tampilkan mapping label
label_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print("Mapping label:", label_mapping)

# === SPLIT TRAIN & TEST ===
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

print(f"Training: {X_train.shape[0]} data")
print(f"Testing : {X_test.shape[0]} data")

# === MODEL TRAINING DAN EVALUASI ===
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Support Vector Machine": SVC(),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42)
}

for name, model in models.items():
    print(f"\n=== {name} ===")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    print(f"Akurasi: {acc:.4f}")
    print("Classification Report:")
    print(classification_report(y_test, y_pred, target_names=le.classes_))

    # === CONFUSION MATRIX VISUAL ===
    ConfusionMatrixDisplay.from_estimator(
        model, X_test, y_test, display_labels=le.classes_,
        cmap='Blues', xticks_rotation=45
    )
    plt.title(f"Confusion Matrix - {name}")
    plt.tight_layout()
    plt.show()